### ISSUE TITLE
Logo is wrong

### ISSUE THREAD

**Issue by supakeen** [supakeen/pinnwand#108]
At some point it seems the custom logo handler stopped working. Write a test and fix.

**Comment by PeGaSuS-Coder** [comment]
Looking forward to have this option available

**Comment by supakeen** [comment]
@PeGaSuS-Coder It's interesting because it seems to work (sometimes), for example it works for the https://bpa.st/ and https://paste.pythondiscord.com/ instances. I'll take another look when I find the time on what's causing this.

**Comment by wookie184** [comment]
It works for paste.pythondiscord.com because we override the default image in the `/static` directory rather than using the `logo_path` parameter https://github.com/python-discord/infra/blob/fab77edceea9328e2eeab164d1df6d061b20c238/kubernetes/namespaces/default/pinnwand/deployment.yaml#L44-L46. I'd guess maybe bpaste is doing something similar?

I think the issue that makes `logo_path` not work is that the `static_path` parameter here
https://github.com/supakeen/pinnwand/blob/3c866b470b2d2df9a53b783416101c44c2b1229a/src/pinnwand/http.py#L86
causes the application to look in the `/static` folder (so it finds the default image) before looking through the routes, so the route that would look up the image using the logo_path is never reached
https://github.com/supakeen/pinnwand/blob/3c866b470b2d2df9a53b783416101c44c2b1229a/src/pinnwand/http.py#L57-L69

**Comment by TehPeGaSuS** [comment]
On [https://bpa.st/](https://bpa.st/) I see the blue bunny and not any custom image.
![bpa-st](https://github.com/supakeen/pinnwand/assets/25697531/f57647df-a62a-40f8-b048-9760c1189ac4)
