### ISSUE TITLE
Tabs can't be typed into the paste input

### ISSUE THREAD

**Issue by nekhvoya** [supakeen/pinnwand#195]
**Steps to reproduce:** 
1. Start typing any text into a paste input field
2. Press 'Tab'

**Actual result:** the tab space isn't typed, the Paste button gets selected instead
https://github.com/supakeen/pinnwand/assets/49349130/ee74b410-14e1-43c8-a2e1-2818288deb5e

**Expected result:** it should be possible to type tabs

**Comment by divSelector** [comment]
This is extremely easy to add because someone already hacked this behavior in for python, but for some reason it didn't occur to them that people besides just python programmers would want it.

https://github.com/supakeen/pinnwand/blob/master/src/pinnwand/static/pinnwand.js#L123-L125

Just remove these lines and it will work.

**Comment by divSelector** [comment]
Just a reminder that I fixed this issue :P

**Comment by supakeen** [comment]
Fixed in #277, thanks @divSelector.
