### ISSUE TITLE
Increase limit to 256kb as discussed

### ISSUE THREAD

**Issue by altendky** [supakeen/pinnwand#21]
for example: https://bpaste.net/show/5n1r

A higher limit would be nice.  256Kb was suggested as likely acceptable.  I believe it is presently 64Kb.

**Comment by supakeen** [comment]
Because the example will be gone in time: increase the limit to at least 256kB perhaps 512kB. Same as this change: https://github.com/supakeen/pinnwand/commit/ec3193cfbd3ca5be192c0ff887d9217ecbe121c7

Note to self (or others): the default mysql text column has a limit of 64kB. We don't want to use a dialect in the models so a size should be passed to the Text column in the models to ensure sqlalchemy selects a large enough column type.
