### ISSUE TITLE
pyproject.toml is missing build-system.build-backend.

### ISSUE THREAD

**Issue by mweinelt** [supakeen/pinnwand#93]
See https://python-poetry.org/docs/pyproject/#poetry-and-pep-517.

```patch
diff --git a/pyproject.toml b/pyproject.toml
index 3c4e87e..8c25269 100644
--- a/pyproject.toml
+++ b/pyproject.toml
@@ -59,4 +59,5 @@ pinnwand = 'pinnwand.__main__:main'
 
 [build-system]
 requires = ["setuptools", "wheel"]
+build-backend = "poetry.masonry.api"
 
```

**Comment by FRidh** [comment]
Actually, this way is not entirely correct either. The thing is, the project seems to be managed using poetry, but then a setuptools-compatible sdist is created.

**Comment by mweinelt** [comment]
Oh yeah, @supakeen please look at the example linked instead for how it's supposed to look.

**Comment by supakeen** [comment]
@mweinelt and @FRidh in commit https://github.com/supakeen/pinnwand/commit/24e23a49676fdec9ea17c8e24aa7cf2458f6c0f0 I've set the build-system + requires to what is linked in the linked documentation. Since I'm not entirely too familiar with the build system can either of you see if this is the correct incantation?

**Comment by mweinelt** [comment]
I'm not smarter than the documentation and this makes the package build on our end.

One more nit is the version number in pyproject.toml, which is stuck at `0.0.0`. https://github.com/supakeen/pinnwand/blob/master/pyproject.toml#L3

```
❯ ls lib/python3.8/site-packages -1
pinnwand
pinnwand-0.0.0.dist-info
```

**Comment by supakeen** [comment]
Mrm yes I know I did that and that it was a bad plan, the build system uses the latest tag due to `poetry-dynamic-versioning` but this doesn't update the dist-info, I'll push a 1.2.1 release in a bit which sets it correctly in `pyproject.toml` so the metadata is correct.

That'll give me some more time to figure out a proper workflow for updating it from the tag information.

**Comment by supakeen** [comment]
Done the 1.2.1 release and closing this ticket after some further chat on IRC.
